filters:
  comments: true
  allowlist:
    allow:
      - "/CHANGELOG\\.md$/"

# https://github.com/sapegin/textlint-rule-terminology
rules:
  terminology:
    exclude:
      - URL
      - website
      - markdown
      - Bug Fixes
      - eslint
      - typescript
      - json
      - node.js
      - id
